version: '3'

output: prefixed

tasks:
  fmt:
    cmds:
      - poetry run black .
      - poetry run ruff check --fix .

  check:
    cmds:
      - task: lint
      - task: test

  lint:
    cmds:
      - poetry run black . --check
      - poetry run ruff check .
      - poetry run mypy .

  test:
    cmds:
      - poetry run pytest {{.CLI_ARGS}}